"""Added order table

Revision ID: 52dea9573d6f
Revises: 7d58def78fdd
Create Date: 2018-10-16 23:03:12.181502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dea9573d6f'
down_revision = '7d58def78fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order',
        sa.Column('row_id', sa.Integer(), nullable=False),
        sa.Column('order_number', sa.String(length=32), nullable=True),
        sa.Column('order_type', sa.Enum('APPLEJUICE', name='ordertype'), nullable=True),
        sa.Column('sender_name', sa.Unicode(length=32), nullable=True),
        sa.Column('receiver_name', sa.Unicode(length=32), nullable=True),
        sa.Column('receiver_phone', sa.String(length=16), nullable=True),
        sa.Column('receiver_addr', sa.Unicode(length=512), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('BEFORE_SEND', 'ON_DELIVERY', 'DELIVERY_COMPLETE', name='orderstatus'), nullable=True),
        sa.Column('paid', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('row_id'),
        sa.UniqueConstraint('order_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
